### ISSUE TITLE
Issue uploading notebook

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/conda-server#169]
@malev 
```
sean$ binstar notebook upload Test\ Data.ipynb -u sean
Using binstar api site http://localhost:4990/api
Test Data.ipynb has been uploaded.
[TypeError] 'bool' object has no attribute '__getitem__' 
Traceback (most recent call last):
  File "/Users/sean/anaconda/bin/binstar", line 9, in <module>
    load_entry_point('binstar==0.10.2.post5', 'console_scripts', 'binstar')()
  File "/Users/sean/Documents/workspace/binstar/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/sean/Documents/workspace/binstar/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/sean/Documents/workspace/binstar/binstar_client/commands/notebook.py", line 111, in upload
    log.info("You can visit your notebook at {}".format(notebook_url(upload_info)))
  File "/Users/sean/Documents/workspace/binstar/binstar_client/utils/notebook/__init__.py", line 33, in notebook_url
    parsed = urlparse(upload_info['url'])
TypeError: 'bool' object has no attribute '__getitem__'
```

**Comment by malev** [comment]
seems to be working for me. closing
