### ISSUE TITLE
binstar notebook download error

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/conda-server#177]
```
mr_chomps:conda-data sean$ binstar notebook download sean/conda_data-ipynb
Using binstar api site https://api.anaconda.org
[IndexError] list index out of range 
Traceback (most recent call last):
  File "/Users/sean/anaconda/bin/binstar", line 9, in <module>
    load_entry_point('binstar==0.10.2.post5', 'console_scripts', 'binstar')()
  File "/Users/sean/Documents/workspace/binstar/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/sean/Documents/workspace/binstar/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/sean/Documents/workspace/binstar/binstar_client/commands/notebook.py", line 126, in download
    log.info("{} has been downloaded as {}.".format(args.handle, download_info[0]))
IndexError: list index out of range
```

@malev

**Comment by malev** [comment]
Happens when there is already a file with the name that will be downloaded
```
➜  tmp  binstar notebook download sean/conda_data-ipynb
Using binstar api site https://api.anaconda.org
sean/conda_data-ipynb has been downloaded as conda_data.ipynb.
➜  tmp  binstar notebook download sean/conda_data-ipynb
Using binstar api site https://api.anaconda.org
[IndexError] list index out of range
Traceback (most recent call last):
  File "/Users/mvanetta/miniconda3/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/mvanetta/miniconda3/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/mvanetta/miniconda3/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/mvanetta/miniconda3/lib/python3.4/site-packages/binstar_client/commands/notebook.py", line 126, in download
    log.info("{} has been downloaded as {}.".format(args.handle, download_info[0]))
IndexError: list index out of range
```
